[package]
name = "dotmatrix"
version.workspace = true
edition.workspace = true

[dependencies]
proc-bitfield.workspace = true

[dev-dependencies]
paste.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
